//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccID { get; set; }
        public string AccStatus { get; set; }
        public decimal Cost { get; set; }
        public decimal Pending { get; set; }
        public int CustID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
