//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int CustID { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public string OrderStatus { get; set; }
        public int laundryID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Laundry Laundry { get; set; }
    }
}
